### ISSUE TITLE
How to use the point cloud shader?

### ISSUE THREAD

**Issue by andybak** [przemyslawzaworski/Unity3D-CG-programming#2]
I've tried applying the script and a material using the shader to a quad and an empty game object.

(It would be fantastic to include a few example scenes in your repo. I can usually work out how to use most of the shaders but occasionally I get stumped)

**Comment by przemyslawzaworski** [comment]
Apply the script to Main Camera and material with shader. Enable DirectX 11 in Player settings. Add fly script to Main Camera to free explore the scene too (for example: https://forum.unity.com/threads/fly-cam-simple-cam-script.67042/). Point cloud shader renders 20 milions particles (but you can change amount by "number" variable) and their movement is generated pseudo-randomly (see video: https://www.youtube.com/watch?v=f5YaTpKI3p8 ).
In the past I implemented also solution for reading *.LAS files (it is common point cloud file format) and then rendering set of points in standalone PC executables (with compute shader support) and second version for Android devices (it was OpenGL ES 2.0 without Graphics.DrawProcedural support, so I had to split point cloud into smaller parts, because Unity has 65 536 vertices limit for single mesh). Video: https://www.youtube.com/watch?v=8dP79qwNtxk . Article is available currently only in Polish language, but if you will be interested, send me private message to e-mail: przemyslawzaworski@gmail.com for more details.

**Comment by przemyslawzaworski** [comment]
And apply script to Main Camera directly without additional quad (because it is not raymarching shader).

**Comment by andybak** [comment]
Ah! It's obvious in hindsight. I have no idea why I didn't think of applying it to the camera.

Looks great in VR. I'm getting 50fps on a GTX 1080. I'm going to play around with the colour and dynamics.

Thanks!
